safe: false
permalink: none
# markdown: kramdown
# markdown: rdiscount
markdown: redcarpet

# The following is custom defined by hass
path:
  archive: /archive.html
  categories: /categories.html
  tags: /tags.html
  uploads: http://202.136.62.195:9099/uploads/