safe: false
permalink: none
markdown: kramdown
kramdown:
  use_coderay: true

# The following is custom defined by hass
path:
  archive: /archive.html
  categories: /categories.html
  tags: /tags.html
  #uploads: http://202.136.62.195:9099/uploads/
  #resources: http://202.136.62.195:9099/
  uploads: http://bugcook.com/uploads/
  resources: http://bugcook.com/
  #uploads: http://localhost/_resource/uploads/
  #resources: http://localhost/_resource/
